name: npm-publish

on:
  push:
    tags:
      - 'v*.*.*'
  workflow_dispatch: {}

permissions:
  contents: read
  id-token: write

jobs:
  publish:
    name: Publish to npm
    runs-on: ubuntu-latest
    environment: npm-publish
    steps:
      - name: Checkout
        uses: actions/checkout@v4

      - name: Setup Node.js
        uses: actions/setup-node@v4
        with:
          node-version: 20

      - name: Install deps (clean)
        run: npm ci

      - name: Prepare OIDC env (unset npmrc)
        shell: bash
        run: |
          echo "Node $(node -v); npm $(npm -v)"
          unset NPM_CONFIG_USERCONFIG || true
          rm -f "$NPM_CONFIG_USERCONFIG" || true

      - name: Publish with provenance (OIDC)
        run: npm publish --provenance
