name: npm-publish

on:
  push:
    tags:
      - 'v*.*.*'
  workflow_dispatch: {}

permissions:
  contents: read
  id-token: write

concurrency: publish-${{ github.ref }}

jobs:
  publish:
    name: Publish to npm
    runs-on: ubuntu-latest
    environment: npm-publish
    steps:
      - name: Checkout
        uses: actions/checkout@v4

      - name: Setup Node.js
        uses: actions/setup-node@v4
        with:
          node-version: 20
          registry-url: 'https://registry.npmjs.org'

      - name: Install deps (clean)
        run: npm ci

      - name: Inspect package (optional)
        run: npm pack --dry-run

      - name: Diagnostics (optional)
        run: |
          echo "Node $(node -v); npm $(npm -v)"
          npm config get registry
          npm whoami || echo "Not logged in yet (expected)"

      - name: Publish with provenance
        run: npm publish --provenance --access public
        env:
          NODE_AUTH_TOKEN: ${{ secrets.NPM_TOKEN }}
